---
title: "Hummus Implementation"
output: html_document
date: "2024-03-10"
---

```{r}
# remotes::install_github("HenrikBengtsson/parallelly", ref="develop")
library(parallelly)
library(future)

# Parallelize the process
parallelly::availableCores(which = "all")
plan(multisession, workers = parallelly::availableCores())

# When you're done, clean up the cluster
stopImplicitCluster()
```

```{r}
plan(multisession, workers = parallelly::availableCores())
# remotes::install_version("Seurat", "4.4.0")
# remotes::install_github("cantinilab/HuMMuS")
library(HuMMuS)
```

# Create an hummus object from seurat object -> Troubleshooting in progress
```{r}
options(Seurat.object.assay.version = 'v4')
# SeuratObject::Version(pbmc)
# SeuratObject::Version(pbmc_new)

# convert a v5 assay to a v3 assay
DefaultAssay(pbmc) <- "SCT"
pbmc[["RNA"]] <- as(object = pbmc[["SCT"]], Class = "Assay")
pbmc[["peaks"]] <- as(object = pbmc[["peaks"]], Class = "Assay")

pbmc_new <- SeuratObject::CreateSeuratObject(pbmc[['RNA']]@counts)
pbmc_new[['peaks']] <- Signac::CreateChromatinAssay(pbmc[['peaks']]@counts)
                                                      
hummus <- as(pbmc_new, 'hummus_object')
```